---

- import_tasks: pre-reqs.yml

- import_tasks: create-vpc.yml
  when:
    - aws_create_vpc
    - operation == "deploy"

- import_tasks: create-subnet.yml
  when:
    - operation == "deploy"

- import_tasks: deploy-cluster.yml
  when:
    - operation == "deploy"

- import_tasks: update_dns.yml
  when:
    - operation == "deploy"

- import_tasks: start_stop_instances.yml
  when: (operation == "running") or
        (operation == "stopped")

- import_tasks: remove_infra.yml
  when:
    - operation == "absent"

- import_tasks: remove_vpc.yml
  when:
    - operation == "absent"
    - delete_vpc
