# Remove OCP Cluster instances
---
- name: Register instances to be terminated
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:env_id": "{{ env_id }}"
  register: destroy_instances

- name: Ensure ec2 are stopped and terminate protection is disabled
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:  "{{ aws_region }}"
    termination_protection: no
    state: stopped
    instance_ids: "{{ item.id }}"
    wait: yes
  with_items:
    - "{{ destroy_instances.instances }}"

- name: Ensure ec2 are terminated
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:  "{{ aws_region }}"
    state: "{{ operation }}"
    instance_ids: "{{ item.id }}"
    wait: yes
  with_items:
    - "{{ destroy_instances.instances }}"

- name: Remove env_id tag to avoid conflicts with same env_id clusters
  ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:  "{{ aws_region }}"
    resource: "{{ item.id }}"
    tags:
      env_id: terminated
  with_items:
    - "{{ destroy_instances.instances }}"
