# Create/update Route 53 zone with new records fro Infra and Master
---
- name: Ensure Route53 zone is present
  route53_zone:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    zone: "{{ dns_domain }}"
    state: present

- name: Update Route53 with OCP master record
  route53:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    zone: "{{ dns_domain }}."
    record: "master-0.{{ env_id }}.{{ dns_domain }}."
    type: A
    value: "{{ master_eip.public_ip }}"
    command: create
    overwrite: yes
    ttl: 300
  when: not ha_mode

- name: Update Route53 with OCP infra wildcard record
  route53:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    zone: "{{ dns_domain }}."
    record: "*.apps.{{ env_id }}.{{ dns_domain }}."
    type: A
    value: "{{ infra_eip.public_ip }}"
    command: create
    overwrite: yes
    ttl: 300
  when: not ha_mode
