---

- hosts: localhost
  pre_tasks:
  - import_tasks: pre-tasks.yml
  roles:
  - role: openshift-ansible-contrib/roles/openstack-stack
    stack_name: "{{ env_id }}.{{ dns_domain }}"
    stack_state: 'absent'
