---
- hosts: seed-hosts
  roles:
  - openshift-ansible-contrib/roles/openshift-pv-cleanup

- import_playbook: delete-openstack.yml
  when:
  - hosting_infrastructure == 'openstack'

- import_playbook: delete-aws.yml
  when:
  - hosting_infrastructure == 'aws'
