---

# Assign hostnames
- hosts: cluster_hosts
  pre_tasks:
  - import_tasks: pre-tasks.yml
  roles:
  - role: openshift-ansible-contrib/roles/hostnames

# Build and process DNS Records
- hosts: localhost
  pre_tasks:
  - import_tasks: pre-tasks.yml
  roles:
  - role: openshift-ansible-contrib/roles/dns-records
  - role: infra-ansible/roles/dns

# provision cinder volume
- import_playbook: cinder-registry.yml
  when:
  - openshift_hosted_registry_storage_kind is defined
  - openshift_hosted_registry_storage_kind == "openstack"
  - openshift_hosted_registry_storage_openstack_volumeID is not defined

