---
# Provision Openstack Instances
- import_playbook: provision-openstack.yml
  when: hosting_infrastructure == "openstack"

# Provision Openstack Instances
- import_playbook: provision-aws.yml
  when: hosting_infrastructure == "aws"
