apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    name: cluster-admin-custom
  rules:
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups: null
    attributeRestrictions: null
    nonResourceURLs:
    - '*'
    resources: []
    verbs:
    - '*'
