---

# 'hosting_infrastructure' is used to drive the correct behavior based
# on the hosting infrastructure, cloud provider, etc. Valid values are:
# - 'openstack'
# - 'aws' (Coming Soon)
# - 'azure' (Coming Soon)
hosting_infrastructure: openstack


# OpenStack Provisioning Variables
# use the "-e" option to set "openstack_ssh_public_key"
#openstack_ssh_public_key:
openstack_default_image_name: "rhel-guest-image-7.3-35.x86_64"
openstack_default_flavor: "m1.medium"
openstack_external_network_name: "external"
openstack_subnet_prefix: 192.168.99
openstack_num_masters: 3
openstack_num_nodes: 2
openstack_num_infra: 1

env_id: "s1-ha"

dns_domain: "casl.example.com"
dns_nameservers:
- 192.168.1.1

docker_volume_size: "10"
docker_storage_block_device: "/dev/vdb"

# Subscription Management Details
# Using Red Hat Satellite:
rhsm_register: True

rhsm_satellite: 'sat-6.example.com'
rhsm_org: 'CASL_ORG'
rhsm_activationkey: 'casl-latest'

rhsm_repos:
 - "rhel-7-server-rpms"
 - "rhel-7-server-ose-3.5-rpms"
 - "rhel-7-server-extras-rpms"
 - "rhel-7-fast-datapath-rpms"

# Or using RHN username, password and optionally pool:
#rhsm_username: ''
#rhsm_password: ''
# leave commented out if you want to `--auto-attach` a pool
#rhsm_pool: ''

